### ISSUE TITLE
Add top level navigation between docs pages

### ISSUE THREAD

**Issue by gustojs** [fratzinger/feathers-trigger#7]
Thanks for updating it for Dove! <3

In the docs there are two pages:

The Guide ([getting-started.md](https://github.com/fratzinger/feathers-trigger/blob/main/docs/getting-started.md))
The API ([hooks.md](https://github.com/fratzinger/feathers-trigger/blob/main/docs/hooks.md)).

However there's no navigation provided to move between them. The only link I've found is in Explanations section, going from getting started page to hooks page.

On top of it, the link is gray so it looks like ordinary text rather than something clickable. 

I can imagine users not realizing there's a separate detailed hooks documentation.

![obraz](https://user-images.githubusercontent.com/25644507/227972435-20c2128b-4af1-474b-9fd0-8c91e2964841.png)

**Comment by fratzinger** [comment]
Thanks for the issue. Always good to know someone actually uses the stuff I produce. 😅

I opened and merged #8 to fix this. I've added back the sidebar. In the crow version I used vuepress. I switched to vitepress and missed adding the sidebar.

I used this gray color because it's the brand color of `feathers-trigger` but you're right: it's not a good UX and also bad A11y. So I switched back to default vitepress coloring for now.
